### ISSUE TITLE
升級到新版本的依賴庫後不能編譯

### ISSUE THREAD

**Issue by ssrlive** [JavaHello/rust-web-example#1]
如題，能否將例子代碼更新到適配新版依賴庫？

**Comment by JavaHello** [comment]
我检查下

**Comment by JavaHello** [comment]
https://github.com/JavaHello/rust-web-example/commit/4dc3e90330742c62dd84d60e2bda993bfc043fb1 已更新

**Comment by ssrlive** [comment]
多謝
